image: node:10.15.0

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - node -v
    - npm -v

deploy:
  stage: deploy
  script:
    - node -v
    - npm -v
    - npm install
    - npm run build:client
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://dev.withwheat.wang/report
  when: manual
  only:
    - /^master$/
