stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build:client

deploy:
  stage: deploy
  script:
    - npm run build:client
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://dev.withwheat.wang/report
  only:
    - /^master$/