image: node:8.15.0-slim

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - node -v
    - npm -v

deploy:
  stage: deploy
  script:
    - node -v
    - npm -v
    - npm install
    - pwd
    - ls -l
    - npm run build:client
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://dev.withwheat.wang/report
  when: manual
  only:
    - /^master$/
