image: node:8.15.0-slim

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

before_script:
  - node -v
  - npm -v
  - pwd

build:
  stage: build
  script:
    - ls -l

deploy:
  stage: deploy
  script:
    - npm install
    - npm run build:client
    - ls -l
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://dev.withwheat.wang/report
  when: manual
  only:
    - /^master$/
